name: 'Publish package to NPM'

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: instal dependencies
        run: npm ci
      -name: run tests
        run: npm run test
      - name: run build
        run: npm run build
      - name: remove src
        run: rm -rf src
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
